ğŸ—ƒï¸ repository:
  - .github/**
  - .gitignore
  - .gitattributes
  - vercel.json
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - LICENSE

ğŸ—ºï¸ maps:
  - maps/**
ğŸ¨ textures:
  - copyrighted/**

"ğŸ› ï¸ app: build":
  - app/build/**
"ğŸ“€ app: client":
  - app/client/**
"ğŸ’¿ app: server":
  - app/server/**
"ğŸ§ª app: tests":
  - app/tests/**

"1ï¸âƒ£ region: kanto":
  - maps/kanto/**
"2ï¸ region: johto":
  - maps/johto/**
"3ï¸ region: hoenn":
  - maps/hoenn/**
"4ï¸ region: sinnoh":
  - maps/sinnoh/**
"5ï¸ region: unova":
  - maps/unova/**
"6ï¸ region: kalos":
  - maps/kalos/**
"7ï¸ region: alola":
  - maps/alola/**
"8ï¸ region: galar":
  - maps/galar/**
"*ï¸âƒ£ region: other":
  - maps/other/**