ğŸ—ƒï¸ repository:
  - .github/**
  - .gitignore
  - .gitattributes
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - scripts.yml
ğŸ› ï¸ build:
  - build/**
ğŸ“€ app (client):
  - client/**
ğŸ¦• deploy:
  - deploy
ğŸ—ºï¸ maps:
  - maps/(!sprites)/**
ğŸ¨ sprites:
  - maps/sprites/**
ğŸ’¿ app (server):
  - server/**
ğŸ§ª tests:
  - tests/**