blank_issues_enabled: true
contact_links:
  - name: ðŸ’¡ Suggest new features
    url: https://github.com/lowlighter/gracidea/discussions/new?category=ideas
    about: Submit ideas to help us improve
  - name: ðŸ’¬ Start a discussion
    url: https://github.com/lowlighter/gracidea/discussions/new?category=general
    about: Ask other questions related to this project here