contact_links:
  - name: ğŸ’¡ Suggest new features
    url: https://github.com/lowlighter/gracidea/discussions/new?category=ideas
    about: Submit ideas to help us improve
  - name: ğŸ™ Request help
    url: https://github.com/lowlighter/gracidea/discussions/new?category=q-a
    about: Ask for help and support
  - name: ğŸ’¬ Start a discussion
    url: https://github.com/lowlighter/gracidea/discussions/new?category=general
    about: Ask other questions related to this project here